/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT MattB_HW8_v2.cdb */

/*  Include Header File  */
#include "MattB_HW8_v2cfg.h"

/*  Config Structures */
/*  Handles  */
